"""initial

Revision ID: e8582c08de70
Revises: 
Create Date: 2023-03-30 10:38:08.448974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8582c08de70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Status',
    sa.Column('idStatus', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idStatus')
    )
    op.create_table('User',
    sa.Column('idUser', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.String(length=45), nullable=False),
    sa.Column('LastName', sa.String(length=45), nullable=False),
    sa.Column('Email', sa.String(length=45), nullable=True),
    sa.Column('Password', sa.String(length=300), nullable=False),
    sa.Column('Phone', sa.String(length=45), nullable=False),
    sa.Column('Role', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Drug',
    sa.Column('idDrug', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('Description', sa.String(length=1000), nullable=True),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('Image', sa.String(length=1000), nullable=False),
    sa.Column('idStatus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idStatus'], ['Status.idStatus'], ),
    sa.PrimaryKeyConstraint('idDrug')
    )
    op.create_table('Order',
    sa.Column('idOrder', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('idStatus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idStatus'], ['Status.idStatus'], ),
    sa.ForeignKeyConstraint(['idUser'], ['User.idUser'], ),
    sa.PrimaryKeyConstraint('idOrder')
    )
    op.create_table('OrderDetails',
    sa.Column('idOrderDetails', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idOrder', sa.Integer(), nullable=False),
    sa.Column('idDrug', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idDrug'], ['Drug.idDrug'], ),
    sa.ForeignKeyConstraint(['idOrder'], ['Order.idOrder'], ),
    sa.PrimaryKeyConstraint('idOrderDetails')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderDetails')
    op.drop_table('Order')
    op.drop_table('Drug')
    op.drop_table('User')
    op.drop_table('Status')
    # ### end Alembic commands ###
